---
title: "tables-graphs"
format: html
---

```{r}
library(tidyverse)
library(here)
Estimated_tariff_impact <- read_csv(here("data","Estimated_Impact_Trump_Tariffs.csv"))
Revenue_effects <- read_csv(here("data", "Revenue_Effects_Trump_Tariffs.csv"))
```

```{r}
est_tariff_impact <- Estimated_tariff_impact |>
  mutate(tariff = ...1) |>
  select(tariff, GDP, `Capital Stock`, `Pre-Tax Wages`,`Hours Worked Converted to Full-Time Equivalent Jobs`) |>
  filter(!is.na(tariff)) |>
  mutate(GDP = str_sub(GDP,3,5)) |>
  mutate(GDP = str_replace(GDP, "ss", ".05")) |>
  mutate(GDP = as.numeric(GDP)) |>
  mutate(`Capital Stock` = str_sub(`Capital Stock`,3,5)) |>
  mutate(`Capital Stock` = str_replace(`Capital Stock`,"ss",".05")) |>
  mutate(`Capital Stock` = as.numeric(`Capital Stock`)) |>
  mutate("GDP_dec" = GDP) |>
  mutate("Capital_stock_dec" = `Capital Stock`) |>
  select(tariff, GDP_dec, Capital_stock_dec)
head(est_tariff_impact)
```

Capital Stock: Capital stock refers to the total number of shares that a company is authorized to issue, as outlined in its corporate charter. It represents the maximum amount of shares the company can ever have outstanding (That can be held by investors). 

```{r}
Revenue_effects <- Revenue_effects |>
  mutate(tariff = `Conventional Revenue`) |>
  select(-`Conventional Revenue`) |>
  relocate(tariff, .before = `2025`) |>
  filter(!is.na(tariff)) |>
  filter(tariff != "Dynamic Revenue")
```

```{r}
Estimated_tariff_impact |>
  head()
Revenue_effects |>
  head()
```



What countries GDP has/will been most effected by the tariffs

```{r}
Rev_effects_long <-Revenue_effects |>
  pivot_longer(cols = c(2:12), names_to = "year", values_to = "est. revenue effect (in billions)")
```

```{r}
Rev_effects_long <- Rev_effects_long |>
  mutate(`est. revenue effect (in billions)` = str_sub(`est. revenue effect (in billions)`, 2,10)) |>
  #mutate(num = str_sub(`est. revenue effect (in billions)`,-1))
  #separate(`est. revenue effect (in billions)`, c("Sign", "Num"))
  mutate(`est. revenue effect (in billions)` = as.numeric(`est. revenue effect (in billions)`))
```


```{r}
Rev_effects_long |>
  filter(year == "2025-2034") |>
  ggplot(aes(x = `est. revenue effect (in billions)`, fill = tariff)) +
  geom_bar()
```

```{r}
Rev_effects_long <- Rev_effects_long |>
  filter(year != "2025-2034") |>
  mutate(year = as.numeric(year))
```

```{r}
Rev_effects_long |>
  ggplot(aes(x=year, y =`est. revenue effect (in billions)`, color = tariff)) +
  geom_line()
```


```{r}
#Change the data types from characters to numerical
ggplot(Estimated_tariff_impact, aes(x = GDP, fill = tariff)) +
  geom_bar()
```

