---
title: "Sedlmayer_K"
format: html
---


>Reflection Point: Build effective teams, 5 ways to strengthen team skills

>Listen carefully and with an open mind. This allows people speak their mind and share ideas to help create a safe space for new ideas.

>Ask thoughtful, curious questions. Questions and constructive criticism is essential for a workplace to grow and accomplsih hard things.

>Challenge your own and others assumptions. Challenging ideas is the only way those ideas will improve. 

>Disagree respectfully. Learn how to disagree and/or criticise people to improve ideas.

>Practice empathy and understand different perspectives. Using empathy we can create a safe and effective workplace.

>Building team chemistry and collective intelligence will further improve teamwork and innovation within work spaces. When people feel welcome and comfortable within a team they are further encouraged to contribute and are generally more effective.

>The main premise of this article is an effort to increase CQ within a workplace. CQ is collective Intelligence which is a groups ability to solve problems and innovate together. It's about the group not the individual.
